site_name: IHC - Cinemark
site_author: Ana, Anne, José e Pedro
site_description: Site voltado para a documentação do Grupo 4 sobre Interação Humano-Computador
repo_url: https://github.com/Interacao-Humano-Computador/2024.2-Grupo04
repo_name: 2024.2-Grupo04

nav:
  - Sobre: index.md

  - Verificações:
    - "Entrega 1":
      - "Lista de verificação": avaliacoes/entrega1/avaliacao.md
      - "Lista de verificação grupo 5": avaliacoes/entrega1/avaliacao+1.md
    - "Entrega 2":
      - "Lista de verificação": avaliacoes/entrega2/avaliacao.md
      - "Lista de verificação grupo 5": avaliacoes/entrega2/avaliacao+1.md
    - "Entrega 3":
      - "Lista de verificação": avaliacoes/entrega3/avaliacao.md
      - "Lista de verificação grupo 5": avaliacoes/entrega3/avaliacao+1.md
    - "Entrega 4":
      - "Lista de verificação": avaliacoes/entrega4/avaliacao.md
      - "Lista de verificação grupo 5": avaliacoes/entrega4/avaliacao+1.md

  - Atas:
    - "Ata 1": Atas/ata1.md

  - Apresentações:
    - "Entrega 2 e 3": apresentacoes/entrega2.md

  - Planejamento:
    - "Cronograma": planejamento/cronograma.md
    - "Sites Avaliados": planejamento/sites-avaliados.md
    - "Site Escolhido" : planejamento/site-escolhido.md
    - "Processo de design" : planejamento/Processo de design.md
    - "Ferramentas": planejamento/ferramentas.md
    - "Mapa de Energia": planejamento/mapa-de-energia.md
  
  - Análise de requisitos:
    - "Aspectos éticos": Analise-de-requisitos/aspectos-eticos.md
    - "Perfil de usuário": Analise-de-requisitos/perfil-de-usuario.md
    - "Cenários": Analise-de-requisitos/cenarios.md
    - "Personas": Analise-de-requisitos/personas.md
    - "Análise de tarefas": Analise-de-requisitos/analise-de-tarefas.md
    - "Princípios gerais de projeto": Analise-de-requisitos/principios-gerais-de-projeto.md
    - "Metas de usabilidade": Analise-de-requisitos/metas-de-usabilidade.md
    - "Guia de estilo": Analise-de-requisitos/guia-de-estilo.md
    - "Características da plataforma": Analise-de-requisitos/caracteristicas-da-plataforma.md

  - Design, Avaliação e Desenvolvimento:
    - "Nível 1":
      - " Análise de tarefas": 
        - " Planejamento da Avaliação do Análise de tarefas": Desing-Avaliação-Desenvolvimento/Analise/avaliacao-analise-tarefas.md
        - " Planejamento do relato dos resultados da avaliação do Análise de tarefas": Desing-Avaliação-Desenvolvimento/Analise/resultado-analise-tarefas.md
      - " Storyboard ": 
        - " Planejamento da Avaliação do Storyboard": Desing-Avaliação-Desenvolvimento/Storyboard/avaliacao-storyboard.md
        - " Planejamento do relato dos resultados da avaliação do Storyboard": Desing-Avaliação-Desenvolvimento/Storyboard/resultado-storyboard.md
        - " Storyboard ": Desing-Avaliação-Desenvolvimento/Storyboard/storyboards.md
        
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer

  disable_nav_previous_next: true

  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Trocar para modo escuro

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Trocar para modo claro

  favicon: assets/favicon.ico
  logo: assets/favicon.ico
  

markdown_extensions:
  - tables
  - attr_list
  - md_in_html


extra_css: [stylesheets/extra.css]